FROM amazoncorretto:17-al2022-jdk
MAINTAINER verellen.com
COPY target/demo_nosql-0.0.1-SNAPSHOT.jar demo_nosql-0.0.1-SNAPSHOT.jar
EXPOSE 8080
EXPOSE 80
ENTRYPOINT ["java","-jar","/demo_nosql-0.0.1-SNAPSHOT.jar"]
